# Generated by Django 4.2.7 on 2024-01-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=25, verbose_name='место выполнения привычки')),
                ('timing', models.TimeField(verbose_name='время выполнения привычки')),
                ('action', models.CharField(max_length=100, verbose_name='действие')),
                ('is_pleasurable', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('frequency', models.CharField(choices=[('daily', 'Ежедневно'), ('monthly', 'Ежемесячно'), ('custom', 'Настраиваемое')], verbose_name='периодичность')),
                ('reward', models.CharField(blank=True, max_length=255, null=True, verbose_name='вознаграждение')),
                ('time_to_perform', models.PositiveSmallIntegerField(verbose_name='время на выполнение')),
                ('is_public', models.BooleanField(default=False, verbose_name='признак публичности')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
